# Generated by Django 3.1.7 on 2021-05-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('city', models.CharField(max_length=40)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=12)),
            ],
        ),
    ]
