# Generated by Django 3.1.7 on 2021-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_customer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
